### ISSUE TITLE
Got Error in plot the results.

### ISSUE THREAD

**Issue by tiru1930** [mukund109/word-mesh#1]
ValueError: 
    Invalid value of type 'builtins.str' received for the 'textposition' property of scatter
        Received value: 'centre'

    The 'textposition' property is an enumeration that may be specified as:
      - One of the following enumeration values:
            ['top left', 'top center', 'top right', 'middle left',
            'middle center', 'middle right', 'bottom left', 'bottom
            center', 'bottom right']
      - A tuple, list, or one-dimensional numpy array of the above

**Comment by mukund109** [comment]
Could you mention what version of plotly you are using :)

**Comment by tiru1930** [comment]
plotly==3.0.0

**Comment by tiru1930** [comment]
Fixed issue with plotly==2.7.0

**Comment by mukund109** [comment]
Thanks for letting me know, I'll fix the requirements, and try to make forward compatible.

**Comment by samrudh** [comment]
I reinstalled plotly==2.7.0. Then again reinstalled wordmesh. Still the same issue.
Do we need to change anything in the code after downgrading plotly?

**Comment by OlliePage** [comment]
> I reinstalled plotly==2.7.0. Then again reinstalled wordmesh. Still the same issue.
> Do we need to change anything in the code after downgrading plotly?

did you find an answer to this?

**Comment by VickyVouk** [comment]
same problem with @OlliePage

**Comment by SingASongForME** [comment]
ValueError: 
    Invalid value of type 'builtins.str' received for the 'textposition' property of scatter
**For Plotly 4.9.0**

**Comment by shihs** [comment]
Change the 'textposition' property to 'to center' works for `plotly==5.0.0`
